import type { Agency, AutomotiveGroup, SourceInvoice } from "@/lib/pass/types";
import { deriveStatus } from "@/lib/pass/completeness";
import { migrateIdentifiedSeal, syncInvoiceFlags } from "@/lib/pass/invoice-flags";

const now = "2026-08-27T18:00:00.000Z";

function source(
  partial: Partial<SourceInvoice> & Pick<SourceInvoice, "id" | "agencyId" | "fileUrl">,
): SourceInvoice {
  const defaults: SourceInvoice = {
    id: "",
    agencyId: "",
    invoiceId: null,
    fileUrl: "",
    vehicleId: null,
    fileId: null,
    label: "",
    documentType: "",
    uuid: "",
    internalFolio: "",
    invoiceDate: "",
    rfcReceptor: "",
    total: null,
    hasSignature: "",
    signatureType: "",
    signatureLocation: "",
    sealsVisible: "",
    identifiedSeal: "",
    sealLocation: "",
    qrPresent: "",
    qrFunctional: "",
    satVerification: "",
    satResult: "",
    amda: false,
    amdaFound: "",
    amdaMatches: "",
    blacklisted: false,
    isFake: false,
    tags: [],
    documentQuality: "",
    dictamen: "",
    qualityReasons: [],
    qualityNotes: "",
    createdAt: now,
  };
  const merged = { ...defaults, ...partial };
  return syncInvoiceFlags({
    ...merged,
    ...migrateIdentifiedSeal(merged.identifiedSeal, merged.sealLocation),
  });
}

export const seedGroups: AutomotiveGroup[] = [
  {
    id: "grp-audi",
    name: "Audi",
    brands: ["Audi"],
    notes: "Marca consolidada desde las primeras fichas de la hoja DB Agencias.",
    createdAt: now,
    updatedAt: now,
  },
];

const agenciesRaw: Array<Omit<Agency, "mapsUrl" | "mapsPlaceName" | "mapsLat" | "mapsLng" | "groupHistory">> = [
  {
    id: "agc-toluca",
    groupId: "grp-audi",
    name: "Audi Center Toluca",
    brand: "Audi",
    legalName: "Automóviles de Alta Tecnología",
    rfc: "AAT070918EV1",
    emitterNumber: "",
    email: "",
    phone: "",
    address: "",
    city: "Toluca",
    municipality: "",
    state: "Estado de México",
    postalCode: "",
    location: "Toluca, Estado de México",
    notes: "",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-4",
        agencyId: "agc-toluca",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/defdf2af-2759-4060-ac11-8855c2d8c48b/0e9180d9-fe98-4b53-b4b8-7e46b0e33811.pdf",
        vehicleId: "defdf2af-2759-4060-ac11-8855c2d8c48b",
        fileId: "0e9180d9-fe98-4b53-b4b8-7e46b0e33811",
        label: "Factura 4",
        documentType: "PDF",
        uuid: "62C5D7E8-8A9A-41A3-831C-9F9BCB5132BD",
        invoiceDate: "2022-10-18",
        rfcReceptor: "JNO050110KF3",
        total: 939600,
        hasSignature: "Sí",
        sealsVisible: "Sí",
        identifiedSeal: "Audi Center Toluca",
        qrPresent: "Sí",
        qrFunctional: "Funcional",
        satVerification: "Sí",
        satResult: "",
        documentQuality: "Buena",
        dictamen: "Buena",
      }),
    ],
  },
  {
    id: "agc-acceso",
    groupId: "grp-audi",
    name: "Acceso Automotriz",
    brand: "Audi",
    legalName: "Acceso Automotriz, S.A. de C.V.",
    rfc: "AAU021216R40",
    emitterNumber: "",
    email: "",
    phone: "",
    address: "Calzada del Valle 340 Oriente, Col. Del Valle",
    city: "San Pedro Garza García",
    municipality: "San Pedro Garza García",
    state: "Nuevo León",
    postalCode: "66220",
    location: "San Pedro Garza García, Nuevo León, México",
    notes: "",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-5",
        agencyId: "agc-acceso",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/a3f14078-a33f-4001-920f-ecc91314340b/6a368737-d675-4006-8486-39479703e090.pdf",
        vehicleId: "a3f14078-a33f-4001-920f-ecc91314340b",
        fileId: "6a368737-d675-4006-8486-39479703e090",
        label: "Factura 5",
        documentType: "PDF",
        uuid: "A21D650C-D422-48EE-86CB-51F38B938CCA",
        internalFolio: "694 DEA",
        invoiceDate: "2016-07-25",
        rfcReceptor: "NABM610720A68",
        total: 338214,
        hasSignature: "No",
        signatureType: "No visible",
        sealsVisible: "Sí",
        identifiedSeal: "Sello digital del CFDI / Sello del SAT",
        qrPresent: "Visible",
        qrFunctional: "No",
        satVerification: "Sí",
        satResult: "Sí",
        documentQuality: "Buena",
        dictamen: "Factura buena con falta de contundencia para validez",
      }),
    ],
  },
  {
    id: "agc-veracruz",
    groupId: "grp-audi",
    name: "Audi Center Veracruz",
    brand: "Audi",
    legalName: "ALSEN CENTER S.A. DE C.V.",
    rfc: "ACE080909LI7",
    emitterNumber: "",
    email: "",
    phone: "(229) 296 08 20",
    address:
      "Boulevard Manuel Ávila Camacho 1889, Flores Magón, Veracruz, Veracruz de Ignacio de la Llave",
    city: "Veracruz",
    municipality: "Veracruz",
    state: "Veracruz",
    postalCode: "91900",
    location: "Veracruz, Veracruz de Ignacio de la Llave, México",
    notes: "",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-6",
        agencyId: "agc-veracruz",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/4099cb8c-3dba-4db6-92b9-967063e69daa/7217d08a-912a-4f64-8b0c-cf7cebc34419.jpeg",
        vehicleId: "4099cb8c-3dba-4db6-92b9-967063e69daa",
        fileId: "7217d08a-912a-4f64-8b0c-cf7cebc34419",
        label: "Factura 6",
        documentType: "Foto",
        uuid: "",
        internalFolio: "UFE000002538",
        invoiceDate: "2019-02-26",
        rfcReceptor: "XAXX010101000",
        total: 664259,
        hasSignature: "Sí",
        signatureType: "Firma autógrafa",
        sealsVisible: "Sí",
        identifiedSeal: "Audi Center Veracruz",
        qrPresent: "Sí",
        qrFunctional: "Sí",
        satVerification: "Sí",
        satResult: "Sí",
        documentQuality: "Regular",
        dictamen: "Buena",
      }),
    ],
  },
  {
    id: "agc-angelopolis",
    groupId: "grp-audi",
    name: "Audi Center Angelópolis",
    brand: "Audi",
    legalName: "ALSEN CENTER S.A. DE C.V.",
    rfc: "ACE080909LI7",
    emitterNumber: "2051",
    email: "",
    phone: "",
    address: "Blvd. Atlixcáyotl No. 2304-A, Col. Reserva Territorial Atlixcáyotl",
    city: "San Andrés Cholula",
    municipality: "San Andrés Cholula",
    state: "Puebla",
    postalCode: "72810",
    location: "San Andrés Cholula, Puebla",
    notes: "",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-7",
        agencyId: "agc-angelopolis",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/6212b8a0-eb16-4126-a7e7-a592ba074312/addc8f2f-0e19-4049-98f3-9ec0ffe47b3c.jpeg",
        vehicleId: "6212b8a0-eb16-4126-a7e7-a592ba074312",
        fileId: "addc8f2f-0e19-4049-98f3-9ec0ffe47b3c",
        label: "Factura 7",
        documentType: "Foto",
        uuid: "",
        internalFolio: "UFE000002579",
        invoiceDate: "2019-08-27",
        rfcReceptor: "XAXX010101000",
        total: 573248.71,
        hasSignature: "Sí",
        signatureType: "Firma autógrafa",
        sealsVisible: "Sí",
        identifiedSeal: "ALSEN CENTER S.A. DE C.V. / Audi Center Angelópolis",
        qrPresent: "Sí",
        qrFunctional: "Fraude",
        satVerification: "No",
        satResult: "No",
        documentQuality: "Mala",
        dictamen: "Mala",
      }),
    ],
  },
  {
    id: "agc-masaryk",
    groupId: "grp-audi",
    name: "Audi Center Masaryk",
    brand: "Audi",
    legalName: "ALDEN GERMANIA, S.A. DE C.V.",
    rfc: "AGE070914UM3",
    emitterNumber: "",
    email: "",
    phone: "",
    address: "Av. Presidente Masaryk No. 207, Col. Polanco",
    city: "Ciudad de México",
    municipality: "Miguel Hidalgo",
    state: "Ciudad de México",
    postalCode: "11560",
    location: "Miguel Hidalgo, Ciudad de México",
    notes: "Dos facturas origen de la misma agencia (hoja: facturas 8 y 9).",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-8",
        agencyId: "agc-masaryk",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/91bed308-2fcc-4ab7-a0e2-c65d42870c00/7e902392-66f6-4c64-8684-9986ec4a2f4d.jpeg",
        vehicleId: "91bed308-2fcc-4ab7-a0e2-c65d42870c00",
        fileId: "7e902392-66f6-4c64-8684-9986ec4a2f4d",
        label: "Factura 8",
        documentType: "Foto",
        uuid: "",
        internalFolio: "ANM5541",
        invoiceDate: "",
        rfcReceptor: "",
        total: 484900,
        hasSignature: "Sí",
        signatureType: "Firma autógrafa",
        sealsVisible: "Sí",
        identifiedSeal: "Audi / ALDEN GERMANIA, S.A. DE C.V.",
        qrPresent: "Sí",
        qrFunctional: "No",
        satVerification: "No",
        satResult: "No",
        documentQuality: "Regular",
        dictamen: "Mala calidad",
      }),
      source({
        id: "src-9",
        agencyId: "agc-masaryk",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/91bed308-2fcc-4ab7-a0e2-c65d42870c00/7e902392-66f6-4c64-8684-9986ec4a2f4d.jpeg",
        vehicleId: "91bed308-2fcc-4ab7-a0e2-c65d42870c00",
        fileId: "7e902392-66f6-4c64-8684-9986ec4a2f4d",
        label: "Factura 9",
        documentType: "Foto",
        uuid: "6F05A4B6-4F47-43E2-A133C5DAF97A",
        internalFolio: "",
        invoiceDate: "2019-05-03",
        rfcReceptor: "XAXX010101000",
        total: 547300,
        hasSignature: "Sí",
        signatureType: "Firma autógrafa",
        sealsVisible: "Sí",
        identifiedSeal: "Audi / ALDEN GERMANIA, S.A. DE C.V.",
        qrPresent: "Sí",
        qrFunctional: "No",
        satVerification: "No",
        satResult: "No",
        documentQuality: "Regular",
        dictamen: "Mala calidad",
      }),
    ],
  },
  {
    id: "agc-laguna",
    groupId: "grp-audi",
    name: "Audi Center Laguna",
    brand: "Audi",
    legalName: "Artec Motors, S.A. de C.V.",
    rfc: "AMO011122265",
    emitterNumber: "",
    email: "",
    phone: "(871) 749 1500",
    address: "Blvd. Independencia No. 220 Pte., Col. Centro",
    city: "Torreón",
    municipality: "Torreón",
    state: "Coahuila",
    postalCode: "27000",
    location: "Torreón, Coahuila",
    notes: "",
    status: "draft",
    createdAt: now,
    updatedAt: now,
    sources: [
      source({
        id: "src-10",
        agencyId: "agc-laguna",
        fileUrl:
          "https://iorqdgnczgxnxbxjuibu.supabase.co/storage/v1/object/public/vehicles/prod/54afc694-0bb3-4816-a34b-265f83f631cd/9ba8c842-584f-44f4-bb59-05a02968e685.pdf",
        vehicleId: "54afc694-0bb3-4816-a34b-265f83f631cd",
        fileId: "9ba8c842-584f-44f4-bb59-05a02968e685",
        label: "Factura 10",
        documentType: "PDF",
        uuid: "D9C7BCE9-10F0-46A1-935A-FC67EF28442E",
        internalFolio: "FM 821",
        invoiceDate: "2019-09-17",
        rfcReceptor: "IDI130705PJ1",
        total: 548500,
        hasSignature: "Sí",
        signatureType: "Firma autógrafa",
        sealsVisible: "Sí",
        identifiedSeal: "Sello con folio 1865",
        qrPresent: "Sí",
        qrFunctional: "Sí",
        satVerification: "Sí",
        satResult: "Sí",
        documentQuality: "Buena",
        dictamen: "Buena",
      }),
    ],
  },
];

export const seedAgencies: Agency[] = agenciesRaw.map((agency) => ({
  ...agency,
  mapsUrl: "",
  mapsPlaceName: "",
  mapsLat: null,
  mapsLng: null,
  groupHistory: [],
  status: deriveStatus(agency),
}));
